const SURAHS = [
  {n:1,name:"الفاتحة",en:"Al-Fatihah",type:"Meccan",verses:7},
  {n:2,name:"البقرة",en:"Al-Baqarah",type:"Medinan",verses:286},
  {n:3,name:"آل عمران",en:"Aal-E-Imran",type:"Medinan",verses:200},
  {n:4,name:"النساء",en:"An-Nisa",type:"Medinan",verses:176},
  {n:5,name:"المائدة",en:"Al-Ma'idah",type:"Medinan",verses:120},
  {n:6,name:"الأنعام",en:"Al-An'am",type:"Meccan",verses:165},
  {n:7,name:"الأعراف",en:"Al-A'raf",type:"Meccan",verses:206},
  {n:8,name:"الأنفال",en:"Al-Anfal",type:"Medinan",verses:75},
  {n:9,name:"التوبة",en:"At-Tawbah",type:"Medinan",verses:129},
  {n:10,name:"يونس",en:"Yunus",type:"Meccan",verses:109},
  {n:11,name:"هود",en:"Hud",type:"Meccan",verses:123},
  {n:12,name:"يوسف",en:"Yusuf",type:"Meccan",verses:111},
  {n:13,name:"الرعد",en:"Ar-Ra'd",type:"Medinan",verses:43},
  {n:14,name:"إبراهيم",en:"Ibrahim",type:"Meccan",verses:52},
  {n:15,name:"الحجر",en:"Al-Hijr",type:"Meccan",verses:99},
  {n:16,name:"النحل",en:"An-Nahl",type:"Meccan",verses:128},
  {n:17,name:"الإسراء",en:"Al-Isra",type:"Meccan",verses:111},
  {n:18,name:"الكهف",en:"Al-Kahf",type:"Meccan",verses:110},
  {n:19,name:"مريم",en:"Maryam",type:"Meccan",verses:98},
  {n:20,name:"طه",en:"Taha",type:"Meccan",verses:135},
  {n:21,name:"الأنبياء",en:"Al-Anbiya",type:"Meccan",verses:112},
  {n:22,name:"الحج",en:"Al-Hajj",type:"Medinan",verses:78},
  {n:23,name:"المؤمنون",en:"Al-Mu'minun",type:"Meccan",verses:118},
  {n:24,name:"النور",en:"An-Nur",type:"Medinan",verses:64},
  {n:25,name:"الفرقان",en:"Al-Furqan",type:"Meccan",verses:77},
  {n:26,name:"الشعراء",en:"Ash-Shu'ara",type:"Meccan",verses:227},
  {n:27,name:"النمل",en:"An-Naml",type:"Meccan",verses:93},
  {n:28,name:"القصص",en:"Al-Qasas",type:"Meccan",verses:88},
  {n:29,name:"العنكبوت",en:"Al-Ankabut",type:"Meccan",verses:69},
  {n:30,name:"الروم",en:"Ar-Rum",type:"Meccan",verses:60},
  {n:31,name:"لقمان",en:"Luqman",type:"Meccan",verses:34},
  {n:32,name:"السجدة",en:"As-Sajdah",type:"Meccan",verses:30},
  {n:33,name:"الأحزاب",en:"Al-Ahzab",type:"Medinan",verses:73},
  {n:34,name:"سبأ",en:"Saba",type:"Meccan",verses:54},
  {n:35,name:"فاطر",en:"Fatir",type:"Meccan",verses:45},
  {n:36,name:"يس",en:"Ya-Sin",type:"Meccan",verses:83},
  {n:37,name:"الصافات",en:"As-Saffat",type:"Meccan",verses:182},
  {n:38,name:"ص",en:"Sad",type:"Meccan",verses:88},
  {n:39,name:"الزمر",en:"Az-Zumar",type:"Meccan",verses:75},
  {n:40,name:"غافر",en:"Ghafir",type:"Meccan",verses:85},
  {n:41,name:"فصلت",en:"Fussilat",type:"Meccan",verses:54},
  {n:42,name:"الشورى",en:"Ash-Shura",type:"Meccan",verses:53},
  {n:43,name:"الزخرف",en:"Az-Zukhruf",type:"Meccan",verses:89},
  {n:44,name:"الدخان",en:"Ad-Dukhan",type:"Meccan",verses:59},
  {n:45,name:"الجاثية",en:"Al-Jathiyah",type:"Meccan",verses:37},
  {n:46,name:"الأحقاف",en:"Al-Ahqaf",type:"Meccan",verses:35},
  {n:47,name:"محمد",en:"Muhammad",type:"Medinan",verses:38},
  {n:48,name:"الفتح",en:"Al-Fath",type:"Medinan",verses:29},
  {n:49,name:"الحجرات",en:"Al-Hujurat",type:"Medinan",verses:18},
  {n:50,name:"ق",en:"Qaf",type:"Meccan",verses:45},
  {n:51,name:"الذاريات",en:"Adh-Dhariyat",type:"Meccan",verses:60},
  {n:52,name:"الطور",en:"At-Tur",type:"Meccan",verses:49},
  {n:53,name:"النجم",en:"An-Najm",type:"Meccan",verses:62},
  {n:54,name:"القمر",en:"Al-Qamar",type:"Meccan",verses:55},
  {n:55,name:"الرحمن",en:"Ar-Rahman",type:"Medinan",verses:78},
  {n:56,name:"الواقعة",en:"Al-Waqi'ah",type:"Meccan",verses:96},
  {n:57,name:"الحديد",en:"Al-Hadid",type:"Medinan",verses:29},
  {n:58,name:"المجادلة",en:"Al-Mujadilah",type:"Medinan",verses:22},
  {n:59,name:"الحشر",en:"Al-Hashr",type:"Medinan",verses:24},
  {n:60,name:"الممتحنة",en:"Al-Mumtahanah",type:"Medinan",verses:13},
  {n:61,name:"الصف",en:"As-Saff",type:"Medinan",verses:14},
  {n:62,name:"الجمعة",en:"Al-Jumu'ah",type:"Medinan",verses:11},
  {n:63,name:"المنافقون",en:"Al-Munafiqun",type:"Medinan",verses:11},
  {n:64,name:"التغابن",en:"At-Taghabun",type:"Medinan",verses:18},
  {n:65,name:"الطلاق",en:"At-Talaq",type:"Medinan",verses:12},
  {n:66,name:"التحريم",en:"At-Tahrim",type:"Medinan",verses:12},
  {n:67,name:"الملك",en:"Al-Mulk",type:"Meccan",verses:30},
  {n:68,name:"القلم",en:"Al-Qalam",type:"Meccan",verses:52},
  {n:69,name:"الحاقة",en:"Al-Haqqah",type:"Meccan",verses:52},
  {n:70,name:"المعارج",en:"Al-Ma'arij",type:"Meccan",verses:44},
  {n:71,name:"نوح",en:"Nuh",type:"Meccan",verses:28},
  {n:72,name:"الجن",en:"Al-Jinn",type:"Meccan",verses:28},
  {n:73,name:"المزمل",en:"Al-Muzzammil",type:"Meccan",verses:20},
  {n:74,name:"المدثر",en:"Al-Muddaththir",type:"Meccan",verses:56},
  {n:75,name:"القيامة",en:"Al-Qiyamah",type:"Meccan",verses:40},
  {n:76,name:"الإنسان",en:"Al-Insan",type:"Medinan",verses:31},
  {n:77,name:"المرسلات",en:"Al-Mursalat",type:"Meccan",verses:50},
  {n:78,name:"النبأ",en:"An-Naba",type:"Meccan",verses:40},
  {n:79,name:"النازعات",en:"An-Nazi'at",type:"Meccan",verses:46},
  {n:80,name:"عبس",en:"Abasa",type:"Meccan",verses:42},
  {n:81,name:"التكوير",en:"At-Takwir",type:"Meccan",verses:29},
  {n:82,name:"الانفطار",en:"Al-Infitar",type:"Meccan",verses:19},
  {n:83,name:"المطففين",en:"Al-Mutaffifin",type:"Meccan",verses:36},
  {n:84,name:"الانشقاق",en:"Al-Inshiqaq",type:"Meccan",verses:25},
  {n:85,name:"البروج",en:"Al-Buruj",type:"Meccan",verses:22},
  {n:86,name:"الطارق",en:"At-Tariq",type:"Meccan",verses:17},
  {n:87,name:"الأعلى",en:"Al-A'la",type:"Meccan",verses:19},
  {n:88,name:"الغاشية",en:"Al-Ghashiyah",type:"Meccan",verses:26},
  {n:89,name:"الفجر",en:"Al-Fajr",type:"Meccan",verses:30},
  {n:90,name:"البلد",en:"Al-Balad",type:"Meccan",verses:20},
  {n:91,name:"الشمس",en:"Ash-Shams",type:"Meccan",verses:15},
  {n:92,name:"الليل",en:"Al-Layl",type:"Meccan",verses:21},
  {n:93,name:"الضحى",en:"Ad-Duhaa",type:"Meccan",verses:11},
  {n:94,name:"الشرح",en:"Ash-Sharh",type:"Meccan",verses:8},
  {n:95,name:"التين",en:"At-Tin",type:"Meccan",verses:8},
  {n:96,name:"العلق",en:"Al-Alaq",type:"Meccan",verses:19},
  {n:97,name:"القدر",en:"Al-Qadr",type:"Meccan",verses:5},
  {n:98,name:"البينة",en:"Al-Bayyinah",type:"Medinan",verses:8},
  {n:99,name:"الزلزلة",en:"Az-Zalzalah",type:"Medinan",verses:8},
  {n:100,name:"العاديات",en:"Al-Adiyat",type:"Meccan",verses:11},
  {n:101,name:"القارعة",en:"Al-Qari'ah",type:"Meccan",verses:11},
  {n:102,name:"التكاثر",en:"At-Takathur",type:"Meccan",verses:8},
  {n:103,name:"العصر",en:"Al-Asr",type:"Meccan",verses:3},
  {n:104,name:"الهمزة",en:"Al-Humazah",type:"Meccan",verses:9},
  {n:105,name:"الفيل",en:"Al-Fil",type:"Meccan",verses:5},
  {n:106,name:"قريش",en:"Quraysh",type:"Meccan",verses:4},
  {n:107,name:"الماعون",en:"Al-Ma'un",type:"Meccan",verses:7},
  {n:108,name:"الكوثر",en:"Al-Kawthar",type:"Meccan",verses:3},
  {n:109,name:"الكافرون",en:"Al-Kafirun",type:"Meccan",verses:6},
  {n:110,name:"النصر",en:"An-Nasr",type:"Medinan",verses:3},
  {n:111,name:"المسد",en:"Al-Masad",type:"Meccan",verses:5},
  {n:112,name:"الإخلاص",en:"Al-Ikhlas",type:"Meccan",verses:4},
  {n:113,name:"الفلق",en:"Al-Falaq",type:"Meccan",verses:5},
  {n:114,name:"الناس",en:"An-Nas",type:"Meccan",verses:6},
];

// Exact Juz start positions (surah:ayah). `from`/`to` kept for back-compat.
const JUZ_DATA = [
  {n:1,from:1,to:2,fromSurah:1,fromAyah:1},
  {n:2,from:2,to:2,fromSurah:2,fromAyah:142},
  {n:3,from:2,to:3,fromSurah:2,fromAyah:253},
  {n:4,from:3,to:4,fromSurah:3,fromAyah:93},
  {n:5,from:4,to:4,fromSurah:4,fromAyah:24},
  {n:6,from:4,to:5,fromSurah:4,fromAyah:148},
  {n:7,from:5,to:6,fromSurah:5,fromAyah:82},
  {n:8,from:6,to:7,fromSurah:6,fromAyah:111},
  {n:9,from:7,to:8,fromSurah:7,fromAyah:88},
  {n:10,from:8,to:9,fromSurah:8,fromAyah:41},
  {n:11,from:9,to:11,fromSurah:9,fromAyah:93},
  {n:12,from:11,to:12,fromSurah:11,fromAyah:6},
  {n:13,from:12,to:13,fromSurah:12,fromAyah:53},
  {n:14,from:14,to:15,fromSurah:15,fromAyah:1},
  {n:15,from:16,to:17,fromSurah:17,fromAyah:1},
  {n:16,from:18,to:18,fromSurah:18,fromAyah:75},
  {n:17,from:18,to:20,fromSurah:21,fromAyah:1},
  {n:18,from:21,to:22,fromSurah:23,fromAyah:1},
  {n:19,from:23,to:25,fromSurah:25,fromAyah:21},
  {n:20,from:25,to:27,fromSurah:27,fromAyah:56},
  {n:21,from:27,to:29,fromSurah:29,fromAyah:46},
  {n:22,from:29,to:33,fromSurah:33,fromAyah:31},
  {n:23,from:33,to:36,fromSurah:36,fromAyah:28},
  {n:24,from:36,to:39,fromSurah:39,fromAyah:32},
  {n:25,from:39,to:41,fromSurah:41,fromAyah:47},
  {n:26,from:41,to:45,fromSurah:46,fromAyah:1},
  {n:27,from:45,to:51,fromSurah:51,fromAyah:31},
  {n:28,from:51,to:57,fromSurah:58,fromAyah:1},
  {n:29,from:57,to:67,fromSurah:67,fromAyah:1},
  {n:30,from:67,to:114,fromSurah:78,fromAyah:1},
];

const API_URL = 'https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/ara-quranuthmanihaf.json';

const EDITION_BASE = 'https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1/editions/';
const TRANSLITERATION_ID = 'ara-quran-la';
const TRANSLITERATION_URL = EDITION_BASE + TRANSLITERATION_ID + '.json';

// English translations (same {quran:[{chapter,verse,text}]} shape as Arabic)
const TRANSLATION_EDITIONS = [
  { id: 'eng-ummmuhammad', label: 'Saheeh International', short: 'Saheeh' },
  { id: 'eng-mustafakhattaba', label: 'The Clear Quran — Mustafa Khattab', short: 'Clear Quran' },
  { id: 'eng-muftitaqiusmani', label: 'Mufti Taqi Usmani', short: 'Usmani' },
];
const DEFAULT_TRANSLATION = 'eng-ummmuhammad';

function editionUrl(id) {
  return EDITION_BASE + id + '.json';
}

// Audio reciters (EveryAyah CDN, per-verse SSSVVV.mp3 naming in each folder)
const RECITERS = [
  { id: 'alafasy', label: 'Mishary Alafasy', short: 'Alafasy', folder: 'Alafasy_128kbps' },
  { id: 'basit-murattal', label: 'Abdul Basit — Murattal', short: 'Basit', folder: 'Abdul_Basit_Murattal_192kbps' },
  { id: 'basit-mujawwad', label: 'Abdul Basit — Mujawwad', short: 'Basit M', folder: 'Abdul_Basit_Mujawwad_128kbps' },
  { id: 'sudais', label: 'As-Sudais', short: 'Sudais', folder: 'Abdurrahmaan_As-Sudais_192kbps' },
  { id: 'muaiqly', label: 'Maher Al-Muaiqly', short: 'Muaiqly', folder: 'MaherAlMuaiqly128kbps' },
  { id: 'shuraym', label: 'Saood ash-Shuraym', short: 'Shuraym', folder: 'Saood_ash-Shuraym_128kbps' },
];
const DEFAULT_RECITER = 'alafasy';
const EVERYAYAH_BASE = 'https://everyayah.com/data/';
